stages:
  - build
  - deploy

services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""
  DOCKER_HOST: tcp://docker:2375

before_script:
  - docker info 

build:
  image: docker:latest
  stage: build
  script:
    - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
    - docker build -t $DOCKER_USERNAME/backend:latest ./backend
    - docker build -t $DOCKER_USERNAME/frontend:latest ./frontend
    - docker push $DOCKER_USERNAME/backend:latest
    - docker push $DOCKER_USERNAME/frontend:latest
  only:
    - main 
deploy:
  stage: deploy
  image: docker:latest
  script:
    - apk add --no-cache openssh-client
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan 157.230.115.210 >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - ssh $SSH_USER@157.230.115.210 "docker pull $DOCKER_USERNAME/backend:latest && docker run -d --name backend -p 8080:8080 $DOCKER_USERNAME/backend:latest"
    - ssh $SSH_USER@157.230.115.210 "docker pull $DOCKER_USERNAME/frontend:latest && docker run -d --name frontend -p 80:4040 $DOCKER_USERNAME/frontend:latest"
  only:
    - main